In [1]:
import numpy as np
from sklearn.svm import SVC

In [2]:
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]]) 
y = np.array([1, 1, 2, 2])

In [3]:
clf = SVC() 
clf.fit(X, y)

/Users/nickkon/.local/share/virtualenvs/itea-intro-ds/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [4]:
clf.predict(X)

array([1, 1, 2, 2])

In [5]:
clf.decision_function(X)

array([-1.00052254, -1.00006594,  1.00029424,  1.00029424])

In [6]:
clf.predict_proba(X)

AttributeError: predict_proba is not available when  probability=False

## With probability

In [7]:
clf = SVC(probability=True) 
clf.fit(X, y)

/Users/nickkon/.local/share/virtualenvs/itea-intro-ds/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [8]:
clf.predict_proba(X)

array([[0.94015524, 0.05984476],
       [0.94008448, 0.05991552],
       [0.05979799, 0.94020201],
       [0.05979799, 0.94020201]])